version: '2'
config: 
  slack_notify: true
  slack_channel: retailiqflow-ci
environment:
  BUILD_IMAGE: 'maven:3.6-jdk-11'
jobs:
  build_main:
    steps:
      - build_image
      - push_image:
          auto_version: "false"
          image: "retailiqflow:{{ .env.BRANCH_NAME }}"
workflows:
  jenkins_pipeline:
    jobs:
      - build_main:
          filters:
            branches:
              only:
                - release 